id = "arctikai-theme"
name = "Arctikai"
version = "0.1.0"
schema_version = 1
authors = ["hexqnt <hexqntlab@gmail.com>"]
description = "A cool-toned, muted, and restrained theme inspired by the Monokai Pro color scheme"
repository = "https://github.com/hexqnt/arctikai-zed"
